#top
set_property PACKAGE_PIN Y18 [get_ports {clk}]
set_property IOSTANDARD LVCMOS33 [get_ports {clk}]
set_property PACKAGE_PIN R1 [get_ports {rst}]
set_property IOSTANDARD LVCMOS33 [get_ports {rst}]
set_property PACKAGE_PIN P1 [get_ports {backspace_button}]
set_property IOSTANDARD LVCMOS33 [get_ports {backspace_button}]
set_property PACKAGE_PIN AA8 [get_ports {boardOrSwCtrl}]
set_property IOSTANDARD LVCMOS33 [get_ports {boardOrSwCtrl}]
#####
set_property PACKAGE_PIN P2 [get_ports {start_pg}]
set_property IOSTANDARD LVCMOS33 [get_ports {start_pg}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN Y19} [get_ports rx]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN V18} [get_ports tx]
#switch for input and test and IndexCtrl 
#band
set_property PACKAGE_PIN P5 [get_ports {InputCtrl}]
set_property IOSTANDARD LVCMOS33 [get_ports {InputCtrl}]

set_property PACKAGE_PIN W4 [get_ports {IO_ReadData[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_ReadData[0]}]
set_property PACKAGE_PIN R4 [get_ports {IO_ReadData[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_ReadData[1]}]
set_property PACKAGE_PIN T4 [get_ports {IO_ReadData[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_ReadData[2]}]
set_property PACKAGE_PIN T5 [get_ports {IO_ReadData[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_ReadData[3]}]
set_property PACKAGE_PIN U5 [get_ports {IO_ReadData[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_ReadData[4]}]
set_property PACKAGE_PIN W6 [get_ports {IO_ReadData[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_ReadData[5]}]
set_property PACKAGE_PIN W5 [get_ports {IO_ReadData[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_ReadData[6]}]
set_property PACKAGE_PIN U6 [get_ports {IO_ReadData[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_ReadData[7]}]
set_property PACKAGE_PIN V5 [get_ports {IO_ReadData[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_ReadData[8]}]
set_property PACKAGE_PIN R6 [get_ports {IO_ReadData[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_ReadData[9]}]
set_property PACKAGE_PIN T6 [get_ports {IO_ReadData[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_ReadData[10]}]
set_property PACKAGE_PIN Y6 [get_ports {IO_ReadData[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_ReadData[11]}]
set_property PACKAGE_PIN AA6 [get_ports {IO_ReadData[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_ReadData[12]}]
set_property PACKAGE_PIN V7 [get_ports {IO_ReadData[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_ReadData[13]}]
set_property PACKAGE_PIN AB7 [get_ports {IO_ReadData[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_ReadData[14]}]
set_property PACKAGE_PIN V9 [get_ports {IO_ReadData[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_ReadData[15]}]

set_property PACKAGE_PIN Y7 [get_ports {test_index[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {test_index[0]}]
set_property PACKAGE_PIN W9 [get_ports {test_index[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {test_index[1]}]
set_property PACKAGE_PIN Y9 [get_ports {test_index[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {test_index[2]}]

#seg_en 8bit
set_property PACKAGE_PIN C19 [get_ports {seg_en[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[0]}]
set_property PACKAGE_PIN E19 [get_ports {seg_en[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[1]}]
set_property PACKAGE_PIN D19 [get_ports {seg_en[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[2]}]
set_property PACKAGE_PIN F18 [get_ports {seg_en[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[3]}]
set_property PACKAGE_PIN E18 [get_ports {seg_en[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[4]}]
set_property PACKAGE_PIN B20 [get_ports {seg_en[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[5]}]
set_property PACKAGE_PIN A20 [get_ports {seg_en[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[6]}]
set_property PACKAGE_PIN A18 [get_ports {seg_en[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[7]}]

#seg_out  8bit
set_property PACKAGE_PIN F15 [get_ports {seg_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[0]}]
set_property PACKAGE_PIN F13 [get_ports {seg_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[1]}]
set_property PACKAGE_PIN F14 [get_ports {seg_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[2]}]
set_property PACKAGE_PIN F16 [get_ports {seg_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[3]}]
set_property PACKAGE_PIN E17 [get_ports {seg_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[4]}]
set_property PACKAGE_PIN C14 [get_ports {seg_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[5]}]
set_property PACKAGE_PIN C15 [get_ports {seg_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[6]}]
set_property PACKAGE_PIN E13 [get_ports {seg_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[7]}]

#leds////////////
set_property PACKAGE_PIN N19 [get_ports {IO_LED_Data[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_LED_Data[16]}]
set_property PACKAGE_PIN M17 [get_ports {IO_LED_Data[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_LED_Data[15]}]
set_property PACKAGE_PIN M16 [get_ports {IO_LED_Data[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_LED_Data[14]}]
set_property PACKAGE_PIN M15 [get_ports {IO_LED_Data[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_LED_Data[13]}]
set_property PACKAGE_PIN K16 [get_ports {IO_LED_Data[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_LED_Data[12]}]
set_property PACKAGE_PIN L16 [get_ports {IO_LED_Data[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_LED_Data[11]}]
set_property PACKAGE_PIN L15 [get_ports {IO_LED_Data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_LED_Data[10]}]
set_property PACKAGE_PIN L14 [get_ports {IO_LED_Data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_LED_Data[9]}]
set_property PACKAGE_PIN J17 [get_ports {IO_LED_Data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_LED_Data[8]}]
set_property PACKAGE_PIN F21 [get_ports {IO_LED_Data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_LED_Data[7]}]
set_property PACKAGE_PIN G22 [get_ports {IO_LED_Data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_LED_Data[6]}]
set_property PACKAGE_PIN G21 [get_ports {IO_LED_Data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_LED_Data[5]}]
set_property PACKAGE_PIN D21 [get_ports {IO_LED_Data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_LED_Data[4]}]
set_property PACKAGE_PIN E21 [get_ports {IO_LED_Data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_LED_Data[3]}]
set_property PACKAGE_PIN D22 [get_ports {IO_LED_Data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_LED_Data[2]}]
set_property PACKAGE_PIN E22 [get_ports {IO_LED_Data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_LED_Data[1]}]
set_property PACKAGE_PIN A21 [get_ports {IO_LED_Data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_LED_Data[0]}]

#keyboard
set_property PACKAGE_PIN M2 [get_ports {col[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col[3]}]
set_property PACKAGE_PIN K6 [get_ports {col[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col[2]}]
set_property PACKAGE_PIN J6 [get_ports {col[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col[1]}]
set_property PACKAGE_PIN L5 [get_ports {col[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col[0]}]
set_property PACKAGE_PIN K4 [get_ports {row[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row[3]}]
set_property PACKAGE_PIN J4 [get_ports {row[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row[2]}]
set_property PACKAGE_PIN L3 [get_ports {row[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row[1]}]
set_property PACKAGE_PIN K3 [get_ports {row[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row[0]}]